class Quiz {
  final int id, answer;
  final String quiz, ask, audio;
  final List<String> optional;
  final Function function;

  Quiz(
      {this.audio,
      this.function,
      this.id,
      this.quiz,
      this.ask,
      this.optional,
      this.answer});
}

const List quiz_new_year_exam1 = [
  {
    'audio': 'assets/audio/n1.opus',
    'id': 1,
    'quiz': 'assets/images/fullshoes.png',
    'ask': 'الطلاب داخل الفصل',
    'optional': [
      'assets/images/1.png',
      'assets/images/2.png',
      'assets/images/3.png',
      'assets/images/4.png',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/n2.opus',
    'id': 2,
    'quiz': 'assets/images/fulltshirt.png',
    'ask': ' الطلاب ينظفون الفصل',
    'optional': [
      'assets/images/5.png',
      'assets/images/6.png',
      'assets/images/02.png',
      'assets/images/002.png',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/n3.opus',
    'id': 3,
    'quiz': 'assets/images/fullball.png',
    'ask': ' الطالب يركب الباص',
    'optional': [
      'assets/images/7.png',
      'assets/images/8.png',
      'assets/images/9.png',
      'assets/images/10.png',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/n4.opus',
    'id': 4,
    'quiz': 'assets/images/fullhp.png',
    'ask': 'التلاميذ يتعاونون في تنظيف الفصل',
    'optional': [
      'assets/images/11.png',
      'assets/images/13.png',
      'assets/images/12.png',
      'assets/images/14.png',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/n5.opus',
    'id': 5,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'يستيقظ التلميذ مبكر',
    'optional': [
      'assets/images/17.png',
      'assets/images/15.png',
      'assets/images/16.png',
      'assets/images/18.png',
    ],
    'answer': 0,
  },
  {
    'audio': 'assets/audio/n_y_1.opus',
    'id': 6,
    'quiz': 'assets/images/fullshoes.png',
    'ask': 'المعلمة تشرح الدرس',
    'optional': [
      'assets/images/1.png',
      'assets/images/2.png',
      'assets/images/q1.jpg',
      'assets/images/4.png',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/n_y_2.opus',
    'id': 7,
    'quiz': 'assets/images/fulltshirt.png',
    'ask': 'الطلاب يجلسون فى الفصل',
    'optional': [
      'assets/images/5.png',
      'assets/images/q2.jpg',
      'assets/images/02.png',
      'assets/images/002.png',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/n_y_3.opus',
    'id': 8,
    'quiz': 'assets/images/fullball.png',
    'ask': 'الشجرة لونها اخضر',
    'optional': [
      'assets/images/7.png',
      'assets/images/8.png',
      'assets/images/q5.jpg',
      'assets/images/10.png',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/n_y_4.opus',
    'id': 9,
    'quiz': 'assets/images/fullhp.png',
    'ask': 'البنت تحمل الحقيبة',
    'optional': [
      'assets/images/11.png',
      'assets/images/q3.jpg',
      'assets/images/13.png',
      'assets/images/12.png',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/n_y_5.opus',
    'id': 10,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'الكتب مختلفة الالوان',
    'optional': [
      'assets/images/17.png',
      'assets/images/12.png',
      'assets/images/14.png',
      'assets/images/q4.jpg',
    ],
    'answer': 3,
  },
];
const List quiz_revision = [
  {
    'id': 1,
    'quiz': 'assets/fullshoes.png',
    'ask': 'الشجرة لونها',
    'optional': [
      'assets/red.png',
      'assets/green.png',
      'assets/yelw.jpg',
    ],
    'answer': 1,
  },
  {
    'id': 2,
    'quiz': 'assets/fulltshirt.png',
    'ask': 'الطماطم لونها',
    'optional': [
      'assets/red.png',
      'assets/black.jpg',
      'assets/yelw.jpg',
    ],
    'answer': 0,
  },
  {
    'id': 3,
    'quiz': 'assets/fullball.png',
    'ask': 'الليمون لونه',
    'optional': [
      'assets/blue.jpg',
      'assets/green.png',
      'assets/yelw.jpg',
    ],
    'answer': 2,
  },
];
const List quiz_revision_missing_char = [
  {
    'id': 1,
    'quiz': 'assets/t5/1#.png',
    'audio': 'assets/audio/r1.ogg',
    'ask': '...لب',
    'optional': [
      'assets/t5/20.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/4.png',
    ],
    'answer': 0,
  },
  {
    'id': 2,
    'quiz': 'assets/t5/2#.png',
    'audio': 'assets/audio/r2.ogg',
    'ask': 'يد...',
    'optional': [
      'assets/t5/5.png',
      'assets/t5/6.png',
      'assets/t5/20.png',
      'assets/t5/8.png',
    ],
    'answer': 2,
  },
  {
    'id': 3,
    'quiz': 'assets/t5/3#.png',
    'audio': 'assets/audio/r3.ogg',
    'ask': 'ي...ف',
    'optional': [
      'assets/t5/9.png',
      'assets/t5/10.png',
      'assets/t5/20.png',
      'assets/t5/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 4,
    'quiz': 'assets/t5/4#.png',
    'audio': 'assets/audio/r4.ogg',
    'ask': 'ا...تري',
    'optional': [
      'assets/t5/1.png',
      'assets/t5/14.png',
      'assets/t5/15.png',
      'assets/t5/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 5,
    'quiz': 'assets/t5/5#.png',
    'audio': 'assets/audio/r5.ogg',
    'ask': 'ا...ترت',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/18.png',
      'assets/t5/19.png',
      'assets/t5/1.png',
    ],
    'answer': 3,
  },
  {
    'id': 6,
    'quiz': 'assets/t5/1#.png',
    'audio': 'assets/audio/r6.ogg',
    'ask': '...تاء',
    'optional': [
      'assets/t5/1.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/4.png',
    ],
    'answer': 0,
  },
];




const List quiz_belady = [
  {
    'id': 1,
    'quiz': 'assets/fullshoes.png',
    'ask': 'الشجرة لونها',
    'optional': [
      'assets/red.png',
      'assets/red.png',
      'assets/green.png',
      'assets/yelw.jpg',
    ],
    'answer': 2,
  },
  {
    'id': 2,
    'quiz': 'assets/fulltshirt.png',
    'ask': 'الطماطم لونها',
    'optional': [
      'assets/red.png',
      'assets/black.jpg',
      'assets/yelw.jpg',
    ],
    'answer': 1,
  },
  {
    'id': 3,
    'quiz': 'assets/fullball.png',
    'ask': 'الليمون لونه',
    'optional': [
      'assets/blue.jpg',
      'assets/green.png',
      'assets/yelw.jpg',
    ],
    'answer': 2,
  },
];
const List quiz_belady_exam1 = [
  {
    'audio': 'assets/audio/b1.opus',
    'id': 1,
    'quiz': 'assets/images/fullshoes.png',
    'ask': 'نهر مياهه واسعه نشرب منها:',
    'optional': [
      'assets/images/b3.jpg',
      'assets/images/b8.jpg',
      'assets/images/b5.jpg',
      'assets/images/b7.jpg',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/b2.opus',
    'id': 2,
    'quiz': 'assets/images/fulltshirt.png',
    'ask': 'ارض عالية لها قمه',
    'optional': [
      'assets/images/b1.jpg',
      'assets/images/b2.jpg',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/b3.opus',
    'id': 3,
    'quiz': 'assets/images/fullball.png',
    'ask': 'صحراء واسعه قليلة المطر :',
    'optional': [
      'assets/images/b2.jpg',
      'assets/images/b3.jpg',
      'assets/images/b1.jpg',
      'assets/images/b7.jpg',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/b4.opus',
    'id': 4,
    'quiz': 'assets/images/fullhp.png',
    'ask': 'جمل يعيش في الصحراء :',
    'optional': [
      'assets/images/b9.jpg',
      'assets/images/b1.jpg',
      'assets/images/b10.jpg',
    ],
    'answer': 0,
  },
  {
    'audio': 'assets/audio/b5.opus',
    'id': 5,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'البئر فاتحه عميقه يحفرها الانسان في جوف الارض للوصول الى الماء:',
    'optional': [
      'assets/images/b3.jpg',
      'assets/images/b5.jpg',
      'assets/images/b11.jpg',
      'assets/images/b8.jpg',
    ],
    'answer': 2,
  },
];
const List quiz_belady_chose = [
  {
    'audio': 'assets/audio/bc1.opus',
    'id': 1,
    'quiz': 'assets/images/fullshoes.png',
    'ask': 'اين يعيش السمك',
    'optional': [
      'assets/images/b1.jpg',
      'assets/images/b2.jpg',
      'assets/images/b3.jpg',
      'assets/images/b4.jpg',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/bc2.opus',
    'id': 2,
    'quiz': 'assets/images/fulltshirt.png',
    'ask': 'اين يعيش الجمل',
    'optional': [
      'assets/images/b5.jpg',
      'assets/images/b1.jpg',
      'assets/images/b6.jpg',
      'assets/images/b2.jpg',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/bc3.opus',
    'id': 3,
    'quiz': 'assets/images/fullball.png',
    'ask': 'نشرب من ماء...',
    'optional': [
      'assets/images/b3.jpg',
      'assets/images/b8.jpg',
      'assets/images/b5.jpg',
      'assets/images/b7.jpg',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/bc4.opus',
    'id': 4,
    'quiz': 'assets/images/fullhp.png',
    'ask': 'هي ارض واسعه قليلة المطر',
    'optional': [
      'assets/images/b8.jpg',
      'assets/images/b1.jpg',
      'assets/images/b7.jpg',
      'assets/images/b3.jpg',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/bc5.opus',
    'id': 5,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'ارض تحيط بها المياه من جميع الجهات',
    'optional': [
      'assets/images/b7.jpg',
      'assets/images/b8.jpg',
      'assets/images/b1.jpg',
      'assets/images/b3.jpg',
    ],
    'answer': 0,
  },
  {
    'audio': 'assets/audio/نجار.ogg',
    'id': 6,
    'quiz': 'assets/images/fullshoes.png',
    'ask': 'يسستخدم المنشار',
    'optional': [
      'assets/images/jobs/اللحام.jpg',
      'assets/images/jobs/طبيب.jpg',
      'assets/images/jobs/نجار.jpg',
      'assets/images/jobs/شرطي.jpg',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/معلم.ogg',
    'id': 7,
    'quiz': 'assets/images/fulltshirt.png',
    'ask': 'يستخدم القلم للكتابه علي السبوره',
    'optional': [
      'assets/images/jobs/شرطي.jpg',
      'assets/images/jobs/معلمه.jpg',
      'assets/images/jobs/طبيب.jpg',
      'assets/images/jobs/مهندس.jpg',
    ],
    'answer': 1,
  },
  {
//    'audio':'assets/audio/n_y_3.opus',
    'id': 8,
    'quiz': 'assets/images/fullball.png',
    'ask': 'يستخدم خرطوم الاطفاء لاخماد الحرائق',
    'optional': [
      'assets/images/jobs/معلمه.jpg',
      'assets/images/jobs/طبيب.jpg',
      'assets/images/jobs/اطفاء.jpg',
      'assets/images/jobs/عامل.jpg',
    ],
    'answer': 2,
  },
  {
//    'audio':'assets/audio/n_y_4.opus',
    'id': 9,
    'quiz': 'assets/images/fullhp.png',
    'ask': 'استخدم اللمشعل للحم الحديد',
    'optional': [
      'assets/images/jobs/مهندس.jpg',
      'assets/images/jobs/اللحام.jpg',
      'assets/images/jobs/اطفاء.jpg',
      'assets/images/jobs/طيار.jpg',
    ],
    'answer': 1,
  },
  {
//    'audio':'assets/audio/n_y_5.opus',
    'id': 10,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'الفلاح يستخدم...لزراعه الارض',
    'optional': [
      'assets/images/jobs/شرطي.jpg',
      'assets/images/jobs/اطفاء.jpg',
      'assets/images/jobs/عامل.jpg',
      'assets/images/jobs/مزارع.jpg',
    ],
    'answer': 3,
  },
  {
    'audio': 'assets/audio/طيار.ogg',
    'id': 11,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'يسافر في الجو بالطائره',
    'optional': [
      'assets/images/jobs/طيار.jpg',
      'assets/images/jobs/عامل.jpg',
      'assets/images/jobs/شرطي.jpg',
      'assets/images/jobs/مزارع.jpg',
    ],
    'answer': 0,
  },
  {
    'audio': 'assets/audio/عامل.ogg',
    'id': 12,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'يتسخدم الجاروف للتنظيف:',
    'optional': [
      'assets/images/jobs/مزارع.jpg',
      'assets/images/jobs/عامل.jpg',
      'assets/images/jobs/شرطي.jpg',
      'assets/images/jobs/معلمه.jpg',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/خباز.ogg',
    'id': 13,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'يستخدم المعجنه لصناعه الخبز:',
    'optional': [
      'assets/images/jobs/معلمه.jpg',
      'assets/images/jobs/شرطي.jpg',
      'assets/images/jobs/خباز.jpg',
      'assets/images/jobs/مهندس.jpg',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/شرطي.ogg',
    'id': 14,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'المسدس يستخدمه...لتحقيق العدالة',
    'optional': [
      'assets/images/jobs/اللحام.jpg',
      'assets/images/jobs/طبيب.jpg',
      'assets/images/jobs/عامل.jpg',
      'assets/images/jobs/شرطي.jpg',
    ],
    'answer': 3,
  },
  {
    'audio': 'assets/audio/مهندس.ogg',
    'id': 15,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'المسطرة يستخدمها...للتخطيط',
    'optional': [
      'assets/images/jobs/مهندس.jpg',
      'assets/images/jobs/نجار.jpg',
      'assets/images/jobs/خباز.jpg',
      'assets/images/jobs/اللحام.jpg',
    ],
    'answer': 0,
  },
];
const List quiz_belady_missing_char = [
  {
    'id': 1,
    'quiz': 'assets/t5/1#.png',
    'ask': ' ...هر',
    'optional': [
      'assets/t5/ن.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/4.png',
    ],
    'answer': 0,
  },
  {
    'id': 2,
    'quiz': 'assets/t5/2#.png',
    'ask': '...حر',
    'optional': [
      'assets/t5/5.png',
      'assets/t5/7.png',
      'assets/t5/6.png',
      'assets/t5/8.png',
    ],
    'answer': 2,
  },
  {
    'id': 3,
    'quiz': 'assets/t5/3#.png',
    'ask': 'ج...ل',
    'optional': [
      'assets/t5/9.png',
      'assets/t5/10.png',
      'assets/t5/6.png',
      'assets/t5/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 4,
    'quiz': 'assets/t5/4#.png',
    'ask': 'بئ...',
    'optional': [
      'assets/t5/ر.jpg',
      'assets/t5/14.png',
      'assets/t5/15.png',
      'assets/t5/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 5,
    'quiz': 'assets/t5/5#.png',
    'ask': 'ق...ر',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/18.png',
      'assets/t5/19.png',
      'assets/t5/13.png',
    ],
    'answer': 3,
  },
  {
    'id': 6,
    'quiz': 'assets/t5/1#.png',
    'ask': 'م...لم',
    'optional': [
      'assets/t5/18.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/4.png',
    ],
    'answer': 0,
  },
  {
    'id': 7,
    'quiz': 'assets/t5/2#.png',
    'ask': '...بيب',
    'optional': [
      'assets/t5/5.png',
      'assets/t5/6.png',
      'assets/t5/ط.png',
      'assets/t5/8.png',
    ],
    'answer': 2,
  },
  {
    'id': 8,
    'quiz': 'assets/t5/3#.png',
    'ask': 'نجا...',
    'optional': [
      'assets/t5/9.png',
      'assets/t5/10.png',
      'assets/t5/ر.jpg',
      'assets/t5/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 9,
    'quiz': 'assets/t5/4#.png',
    'ask': 'م...ندس',
    'optional': [
      'assets/missing_char/هه.png',
      'assets/t5/14.png',
      'assets/t5/15.png',
      'assets/t5/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 10,
    'quiz': 'assets/t5/5#.png',
    'ask': 'لح...م',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/18.png',
      'assets/t5/19.png',
      'assets/missing_char/ا.png',
    ],
    'answer': 3,
  },
  {
    'id': 11,
    'quiz': 'assets/t5/1#.png',
    'ask': '...يار',
    'optional': [
      'assets/t5/ط.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/4.png',
    ],
    'answer': 0,
  },
  {
    'id': 12,
    'quiz': 'assets/t5/2#.png',
    'ask': 'عامل ن...افه',
    'optional': [
      'assets/t5/5.png',
      'assets/t5/6.png',
      'assets/missing_char/ظ.png',
      'assets/t5/8.png',
    ],
    'answer': 2,
  },
  {
    'id': 13,
    'quiz': 'assets/t5/3#.png',
    'ask': 'شرط...',
    'optional': [
      'assets/t5/9.png',
      'assets/t5/10.png',
      'assets/t5/14.png',
      'assets/t5/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 14,
    'quiz': 'assets/t5/4#.png',
    'ask': 'رجل اط...اء',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/14.png',
      'assets/t5/15.png',
      'assets/t5/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 15,
    'quiz': 'assets/t5/5#.png',
    'ask': 'مزا...ع',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/18.png',
      'assets/t5/19.png',
      'assets/t5/ر.jpg',
    ],
    'answer': 3,
  },
];

const List quiz_lib_chose = [
  {
    'audio': 'assets/audio/lc1.opus',
    'id': 1,
    'quiz': 'assets/images/fullshoes.png',
    'ask': 'مع من نذهب إلى المكتبه؟',
    'optional': [
      'assets/images/l1.jpg',
      'assets/images/l2.jpg',
      'assets/images/l3.jpg',
      'assets/images/l4.jpg',
    ],
    'answer': 0,
  },
  {
    'audio': 'assets/audio/lc2.opus',
    'id': 2,
    'quiz': 'assets/images/fulltshirt.png',
    'ask': 'ماذا نفعل في المكتبة؟',
    'optional': [
      'assets/images/l6.jpg',
      'assets/images/l7.jpg',
      'assets/images/l5.jpg',
      'assets/images/l8.jpg',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/lc3.opus',
    'id': 3,
    'quiz': 'assets/images/fullball.png',
    'ask': 'أين توجد المكتبه؟',
    'optional': [
      'assets/images/l12.jpg',
      'assets/images/l11.jpg',
      'assets/images/l10.jpg',
      'assets/images/l9.jpg',
    ],
    'answer': 3,
  },
  {
    'audio': 'assets/audio/lc4.opus',
    'id': 4,
    'quiz': 'assets/images/fullhp.png',
    'ask': 'كيف نترك المكتبة؟',
    'optional': [
      'assets/images/l14.png',
      'assets/images/l13.jpg',
      'assets/images/l15.jpg',
      'assets/images/l16.jpg',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/lc5.opus',
    'id': 5,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'من تحكي لنا القصص في المكتبه المدرسيه؟',
    'optional': [
      'assets/images/l17.jpg',
      'assets/images/l3.jpg',
      'assets/images/l18.jpg',
      'assets/images/l19.jpg',
    ],
    'answer': 0,
  },
  {
    'audio': 'assets/audio/lc6.ogg',
    'id': 6,
    'quiz': 'assets/images/fullshoes.png',
    'ask': 'ماذا يوجد في المكتبه؟',
    'optional': [
      'assets/images/l21.jpg',
      'assets/images/l22.jpg',
      'assets/images/l24.jpg',
      'assets/images/l11.jpg',
    ],
    'answer': 2,
  },
  {
    'audio': 'assets/audio/lc7.ogg',
    'id': 7,
    'quiz': 'assets/images/fulltshirt.png',
    'ask': 'أين نقرأ الكتب؟',
    'optional': [
      'assets/images/l9.jpg',
      'assets/images/l13.jpg',
      'assets/images/l11.jpg',
      'assets/images/l10.jpg',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/lc8.opus',
    'id': 8,
    'quiz': 'assets/images/fullhp.png',
    'ask': 'جمع كلمة كتاب',
    'optional': [
      'assets/images/lc2.png',
      'assets/images/lc1.png',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/lc9.opus',
    'id': 9,
    'quiz': 'assets/images/fullmedia.png',
    'ask': 'جمع كلمة لعبة',
    'optional': [
      'assets/images/lc3.png',
      'assets/images/lc4.png',
    ],
    'answer': 1,
  },
  {
    'audio': 'assets/audio/lc10.ogg',
    'id': 10,
    'quiz': 'assets/images/fullshoes.png',
    'ask': 'جمع كلمة مدرسة',
    'optional': [
      'assets/images/lc5.png',
      'assets/images/lc6.png',
    ],
    'answer': 0,
  },
  {
    'audio': 'assets/audio/lc11.ogg',
    'id': 11,
    'quiz': 'assets/images/fulltshirt.png',
    'ask': 'جمع كلمة تلميذ',
    'optional': [
      'assets/images/lc7.png',
      'assets/images/lc8.png',
    ],
    'answer': 1,
  },
];
const List quiz_lib_missing_char = [
  {
    'id': 1,
    'quiz': 'assets/t5/1#.png',
    'ask': 'مكت...ة',
    'optional': [
      'assets/t5/1.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/6.png',
    ],
    'answer': 3,
  },
  {
    'id': 2,
    'quiz': 'assets/t5/2#.png',
    'ask': 'مد...سه',
    'optional': [
      'assets/t5/ر.jpg',
      'assets/t5/6.png',
      'assets/t5/7.png',
      'assets/t5/8.png',
    ],
    'answer': 0,
  },
  {
    'id': 3,
    'quiz': 'assets/t5/3#.png',
    'ask': 'ق...ه',
    'optional': [
      'assets/t5/9.png',
      'assets/t5/10.png',
      'assets/t5/2.png',
      'assets/t5/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 4,
    'quiz': 'assets/t5/4#.png',
    'ask': '...تب',
    'optional': [
      'assets/t5/ك.png',
      'assets/t5/14.png',
      'assets/t5/15.png',
      'assets/t5/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 5,
    'quiz': 'assets/t5/5#.png',
    'ask': '...لاميذ',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/18.png',
      'assets/t5/19.png',
      'assets/t5/16.png',
    ],
    'answer': 3,
  },
  {
    'id': 6,
    'quiz': 'assets/t5/1#.png',
    'ask': 'في مدرستي ...كتبة كبيرة.',
    'optional': [
      'assets/t5/1.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/13.png',
    ],
    'answer': 3,
  },
  {
    'id': 7,
    'quiz': 'assets/t5/2#.png',
    'ask': 'نتر... المكتبة نظيفة مرتبة.',
    'optional': [
      'assets/t5/ك.png',
      'assets/t5/6.png',
      'assets/t5/7.png',
      'assets/t5/8.png',
    ],
    'answer': 0,
  },
  {
    'id': 8,
    'quiz': 'assets/t5/5#.png',
    'ask': 'في المكتبة ن...رأ',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/18.png',
      'assets/t5/19.png',
      'assets/t5/20.png',
    ],
    'answer': 3,
  },
  {
    'id': 9,
    'quiz': 'assets/t5/1#.png',
    'ask': 'في المكتبة نر...م',
    'optional': [
      'assets/t5/1.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/س.png',
    ],
    'answer': 3,
  },
  {
    'id': 9,
    'quiz': 'assets/t5/2#.png',
    'ask': 'في المكتبة نكت...',
    'optional': [
      'assets/t5/1.png',
      'assets/t5/6.png',
      'assets/t5/7.png',
      'assets/t5/8.png',
    ],
    'answer': 1,
  },
];



const List quiz_exam3 = [
  {
    'id': 1,
    'quiz': 'assets/fullshoes.png',
    'ask': 'فصل ',
    'optional': [
      'assets/t3/1.png',
      'assets/t3/2.png',
      'assets/t3/3.png',
      'assets/t3/4.png',
    ],
    'answer': 1,
  },
  {
    'id': 2,
    'quiz': 'assets/fulltshirt.png',
    'ask': '  سبوره',
    'optional': [
      'assets/t3/5.png',
      'assets/t3/6.png',
      'assets/t3/7.png',
      'assets/t3/8.png',
    ],
    'answer': 2,
  },
  {
    'id': 3,
    'quiz': 'assets/fullball.png',
    'ask': '   ممحاة',
    'optional': [
      'assets/t3/9.png',
      'assets/t3/10.png',
      'assets/t3/11.png',
      'assets/t3/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 4,
    'quiz': 'assets/fullhp.png',
    'ask': ' ولد ',
    'optional': [
      'assets/t3/13.png',
      'assets/t3/14.png',
      'assets/t3/15.png',
      'assets/t3/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 5,
    'quiz': 'assets/fullmedia.png',
    'ask': '.....   ملعب  ',
    'optional': [
      'assets/t3/17.png',
      'assets/t3/18.png',
      'assets/t3/19.png',
      'assets/t3/20.png',
    ],
    'answer': 1,
  },
  {
    'id': 6,
    'quiz': 'assets/fullmedia.png',
    'ask': '.....   مقعد  ',
    'optional': [
      'assets/t3/17.png',
      'assets/t3/18.png',
      'assets/t3/19.png',
      'assets/t3/20.png',
    ],
    'answer': 1,
  },
];

const List quiz_new_year_chose = [
  {
    'id': 1,
    'quiz': 'assets/fullshoes.png',
    'audio': 'assets/audio/n_y_c_1.opus',
    'ask': ' ماذا يرتدي التلميذ في المدرسة ',
    'optional': [
      'assets/t2/1.png',
      'assets/t2/2.png',
      'assets/t2/3.png',
      'assets/t2/4.png',
    ],
    'answer': 3,
  },
  {
    'id': 2,
    'quiz': 'assets/fulltshirt.png',
    'audio': 'assets/audio/n_y_c_2.opus',
    'ask': '   ماذا يوجد داخل الحقيبة؟',
    'optional': [
      'assets/t2/5.png',
      'assets/t2/6.png',
      'assets/t2/7.png',
      'assets/t2/8.png',
    ],
    'answer': 3,
  },
  {
    'id': 3,
    'quiz': 'assets/fullball.png',
    'audio': 'assets/audio/n_y_c_3.opus',
    'ask': '    ماذا نستخدم لتنظيف الفصل ؟ ',
    'optional': [
      'assets/t2/9.png',
      'assets/t2/10.png',
      'assets/t2/11.png',
      'assets/t2/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 4,
    'quiz': 'assets/fullhp.png',
    'audio': 'assets/audio/n_y_c_4.opus',
    'ask': '  اين يذهب التلاميذ صباحا؟',
    'optional': [
      'assets/t2/13.png',
      'assets/t2/14.png',
      'assets/t2/15.png',
      'assets/t2/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 5,
    'quiz': 'assets/fullmedia.png',
    'audio': 'assets/audio/n_y_c_5.opus',
    'ask': ' ماذا نحتاج لكتابة الدرس؟ ',
    'optional': [
      'assets/t2/18.png',
      'assets/t2/17.png',
      'assets/t2/6.png',
      'assets/t2/2.png',
    ],
    'answer': 1,
  },
  {
    'id': 6,
    'quiz': 'assets/fullmedia.png',
    'audio': 'assets/audio/n_y_c_6.opus',
    'ask': 'كيف يجلس التلميذ فصل ؟',
    'optional': [
      'assets/t2/n_y_1.jpg',
      'assets/t2/17.png',
      'assets/t2/14.png',
      'assets/t2/15.png',
    ],
    'answer': 0,
  },
  {
    'id': 7,
    'quiz': 'assets/fulltshirt.png',
    'audio': 'assets/audio/n_y_c_7.opus',
    'ask': 'من يذهب الى المدرسة؟',
    'optional': [
      'assets/t2/5.png',
      'assets/t2/6.png',
      'assets/t2/7.png',
      'assets/t2/q1.jpg',
    ],
    'answer': 3,
  },
  {
    'id': 8,
    'quiz': 'assets/fullball.png',
    'audio': 'assets/audio/n_y_c_8.opus',
    'ask': 'من يشرح فى الفصل؟',
    'optional': [
      'assets/t2/9.png',
      'assets/t2/10.png',
      'assets/t2/q2.jpg',
      'assets/t2/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 9,
    'quiz': 'assets/fullhp.png',
    'audio': 'assets/audio/n_y_c_9.opus',
    'ask': ' ماذا يوجد فى حديقة المدرسة؟',
    'optional': [
      'assets/t2/q3.jpg',
      'assets/t2/14.png',
      'assets/t2/15.png',
      'assets/t2/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 10,
    'quiz': 'assets/fullmedia.png',
    'audio': 'assets/audio/n_y_c_10.opus',
    'ask': 'ماذا نستخدم لكى نكتب الدرس؟',
    'optional': [
      'assets/t2/18.png',
      'assets/t2/q4.jpg',
      'assets/t2/6.png',
      'assets/t2/2.png',
    ],
    'answer': 1,
  },
  {
    'id': 11,
    'quiz': 'assets/fullmedia.png',
    'audio': 'assets/audio/n_y_c_11.opus',
    'ask': 'ما هو جمع ولد؟',
    'optional': [
      'assets/t2/q5.jpg',
      'assets/t2/17.png',
      'assets/t2/14.png',
      'assets/t2/15.png',
    ],
    'answer': 0,
  },
];
const List quiz_new_year_missing_char = [
  {
    'id': 1,
    'quiz': 'assets/t5/1#.png',
    'ask': ' ن...اط',
    'optional': [
      'assets/t5/1.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/4.png',
    ],
    'answer': 0,
  },
  {
    'id': 2,
    'quiz': 'assets/t5/2#.png',
    'ask': ' تنظ...م ',
    'optional': [
      'assets/t5/5.png',
      'assets/t5/6.png',
      'assets/t5/7.png',
      'assets/t5/8.png',
    ],
    'answer': 2,
  },
  {
    'id': 3,
    'quiz': 'assets/t5/3#.png',
    'ask': 'تعاو...',
    'optional': [
      'assets/t5/9.png',
      'assets/t5/10.png',
      'assets/t5/11.png',
      'assets/t5/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 4,
    'quiz': 'assets/t5/4#.png',
    'ask': '...ساعدة',
    'optional': [
      'assets/t5/13.png',
      'assets/t5/14.png',
      'assets/t5/15.png',
      'assets/t5/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 5,
    'quiz': 'assets/t5/5#.png',
    'ask': ' حدي...ة  ',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/18.png',
      'assets/t5/19.png',
      'assets/t5/20.png',
    ],
    'answer': 3,
  },
  {
    'id': 6,
    'quiz': 'assets/t5/1#.png',
    'ask': 'ول...',
    'optional': [
      'assets/t5/د.png',
      'assets/t5/2.png',
      'assets/t5/3.png',
      'assets/t5/4.png',
    ],
    'answer': 0,
  },
  {
    'id': 7,
    'quiz': 'assets/t5/2#.png',
    'ask': '...لم',
    'optional': [
      'assets/t5/5.png',
      'assets/t5/6.png',
      'assets/t5/ق.png',
      'assets/t5/8.png',
    ],
    'answer': 2,
  },
  {
    'id': 8,
    'quiz': 'assets/t5/3#.png',
    'ask': 'ك...ب',
    'optional': [
      'assets/t5/9.png',
      'assets/t5/10.png',
      'assets/t5/16.png',
      'assets/t5/12.png',
    ],
    'answer': 2,
  },
  {
    'id': 9,
    'quiz': 'assets/t5/4#.png',
    'ask': '...صل',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/14.png',
      'assets/t5/15.png',
      'assets/t5/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 10,
    'quiz': 'assets/t5/5#.png',
    'ask': 'ب...ت',
    'optional': [
      'assets/t5/17.png',
      'assets/t5/18.png',
      'assets/t5/19.png',
      'assets/t5/ن.png',
    ],
    'answer': 3,
  },
];

const List quiz_q_a = [
  {
    'id': 1,
    'quiz': 'assets/fullshoes.png',
    'audio': 'assets/audio/n_y_qa_1.opus',
    'ask': '  من الذي ينظف الفصل؟  ',
    'optional': [
      'assets/t6/1.png',
      'assets/t6/2.png',
      'assets/t6/3.png',
      'assets/t6/4.png',
    ],
    'answer': 2,
  },
  {
    'id': 2,
    'quiz': 'assets/fulltshirt.png',
    'audio': 'assets/audio/n_y_qa_2.opus',
    'ask': ' من الذي يرحب بالتلاميذ في الفصل ؟ ',
    'optional': [
      'assets/t6/5.png',
      'assets/t6/6.png',
      'assets/t6/7.png',
      'assets/t6/8.png',
    ],
    'answer': 1,
  },
  {
    'id': 3,
    'quiz': 'assets/fullball.png',
    'audio': 'assets/audio/n_y_qa_3.opus',
    'ask': '  يكتب المعلم علي',
    'optional': [
      'assets/t6/9.png',
      'assets/t6/10.png',
      'assets/t6/11.png',
      'assets/t6/12.png',
    ],
    'answer': 1,
  },
  {
    'id': 4,
    'quiz': 'assets/fullhp.png',
    'audio': 'assets/audio/n_y_qa_4.opus',
    'ask': 'ماذا يحمل التلميذ',
    'optional': [
      'assets/t6/14.png',
      'assets/t6/13.png',
      'assets/t6/15.png',
      'assets/t6/16.png',
    ],
    'answer': 0,
  },
  {
    'id': 5,
    'quiz': 'assets/fullmedia.png',
    'audio': 'assets/audio/n_y_qa_5.opus',
    'ask': ' اين المدرس ',
    'optional': [
      'assets/t6/17.png',
      'assets/t6/19.png',
      'assets/t6/18.png',
      'assets/t6/20.png',
    ],
    'answer': 2,
  },
];

const List quiz_qanatir = [
  {
    'id': 1,
    'quiz': 'assets/fullshoes.png',
//    'audio':'assets/audio/n1.opus',
    'ask': '1-ذهب التلاميذ الرحله ب:',
    'optional': [
      'assets/q_1/q1.jpg',
      'assets/q_1/q2.jpg',
    ],
    'answer': 1,
  },
  {
    'id': 2,
    'quiz': 'assets/fulltshirt.png',
//    'audio':'assets/audio/n1.opus',
    'ask': '2-ماذا شاهد التلاميذ أثناء السير على الطريقه:',
    'optional': [
      'assets/q_1/q3.jpg',
      'assets/q_1/q4.jpg',
    ],
    'answer': 1,
  },
  {
    'id': 1,
    'quiz': 'assets/fullball.png',
//    'audio':'assets/audio/n1.opus',
    'ask': '3-ماذا شاهد التلاميذعندما وصلوا الرحله:',
    'optional': [
      'assets/q_1/q6.jpg',
      'assets/q_1/q5.jpg',
    ],
    'answer': 0,
  },
];
const List quiz_qanatir_missing_char = [
  {
    'id': 1,
    'quiz': 'assets/fullshoes.png',
//    'audio':'assets/audio/n1.opus',
    'ask': '١-رح...ة',
    'optional': [
      'assets/missing_char/ل.jpg',
      'assets/missing_char/ا.png',
    ],
    'answer': 0,
  },
  {
    'id': 2,
    'quiz': 'assets/fulltshirt.png',
//    'audio':'assets/audio/n1.opus',
    'ask': '٢-ن...ام',
    'optional': [
      'assets/missing_char/ش.png',
      'assets/missing_char/ظ.png',
      'assets/missing_char/ا.png',
    ],
    'answer': 1,
  },
  {
    'id': 1,
    'quiz': 'assets/fullball.png',
//    'audio':'assets/audio/n1.opus',
    'ask': '٣-ب...ص',
    'optional': [
      'assets/missing_char/ت.png',
      'assets/missing_char/ظ.png',
      'assets/missing_char/ا.png',
      'assets/missing_char/ش.png',
    ],
    'answer': 2,
  },
];
